.TH regionset 8 "5 Jan 2004"
.SH NAME
regionset \- display and set the zone setting of a DVD drive
.SH SYNOPSIS
.B regionset
.RI [ device ]
.SH DESCRIPTION
.B regionset
is a small utility which displays and sets
the region/zone setting of a DVD drive, allowing it to decrypt
the DVD's sold in this geographical area.
.SH OPTIONS
.TP
.I device
The device corresponding to the DVD drive.
.SH SEE ALSO
This program is documented fully in
.IR /usr/share/doc/regionset/README .
.SH AUTHOR
Mirko D\[:o]lle <cooper@linvdr.org>.
.P
This manual page was written by Josselin Mouette <joss@debian.org>,
for the Debian project (but may be used by others).
